var alo={ms:0,md:0,me:0,e:function(e,a,d){d=document.createElement(a);"script"==a&&(d.async=!0,setTimeout(function(){document.getElementsByTagName("script")[0].remove()},500));e=document.createTextNode(e);d.appendChild(e);document.getElementsByTagName("head")[0].appendChild(d)},c:function(e,a,d,k,f,g){a=void 0===a?null:a;d=void 0===d?null:d;f=void 0===f?null:f;g=void 0===g?null:g;var b=new XMLHttpRequest;g&&$.lg(1);b.onreadystatechange=function(){if(4==b.readyState&&200==b.status){g&&$.lg(0);var h=
b.responseText;alo.e(h,k,g);f&&f();if("undefined"!==typeof Storage){0<e.indexOf("&ddos=")&&(h=h.split(");"),h.shift(),h=h.join(");"));if("/"==h[0]){var c=h.split('},"category":[{'),h=c[0];c.shift();c=c.join('},"category":[{').split('}],"title":{');c.shift();h=h+'},"title":{'+c.join('}],"title":{')}d&&localStorage.setItem(a,JSON.stringify({content:h,version:d}));"undefined"!==typeof sow&&sow.cae()}}};b.open("GET",e,!0);b.send()},p:function(e,a){this.ms=e;this.md=a;this.me=(new Date).getTime();localStorage.setItem("a.start",
this.me);localStorage.setItem("a.google",JSON.stringify({content:"var googles = {ms:"+e+",md:"+a+"};",version:"1"}))},$:function(e,a,d,k,f,g){a=void 0===a?null:a;d=void 0===d?null:d;k=void 0===k?null:k;f=void 0===f?null:f;if(g=void 0===g?null:g)sow.src=e;if(a&&"n"!=a[0]&&0<e.indexOf("/exec?")&&0>e.indexOf("&ddos="))if(0!=this.ms){var b=Math.floor(((new Date).getTime()-this.me)/1E3);this.$(e+"&ddos="+(this.ms+b)+"&dos="+this.md+"&end="+b,a,d,k,f,g)}else var h=setInterval(function(){if("object"==typeof googles){clearInterval(h);
var b=localStorage.getItem("a.start"),c;null!=b?(c=(new Date).getTime(),b=Math.floor((c-parseInt(b))/1E3),b=googles.ms+b,c=7*(b-173472337)):(b=googles.ms,c=googles.md);alo.$(e+"&ddos="+b+"&dos="+c+"&end=0",a,d,k,f,g)}},100);else{var b=Math.ceil((new Date).getTime()/1E3),c=localStorage,l=0;if(k&&0!=k){for(var m in c)if(0==m.indexOf(a)){0==m.indexOf(a+"-")?l=m:c.removeItem(m);break}0!=l?(m=l.split("-"),m=+m[1],m<b?(c.removeItem(l),a+="-"+(b+ +k)):a=l):a+="-"+(b+ +k)}b=c.getItem(a);c=0<e.indexOf(".css")?
"style":"script";null!=b&&null!=d?(l=JSON.parse(b),l.version==d?(this.e(l.content,c,g),f&&f()):(localStorage.removeItem(b),this.c(e,a,d,c,f,g))):this.c(e,a,d,c,f,g)}}};

alo.$('https://script.google.com/macros/s/AKfycbxBh5ptSSej3stcLyB1k_oIuVXuKvGLzsdc7LFL2I4xe4APdaA/exec','a.google','1');
alo.$('https://rongnano.github.io/file/js.js','a.js','7');
alo.$('https://rongnano.github.io/file/style.css','a.css','7');
