var alo={ms:0,md:0,me:0,e:function(c,b,d){d=document.createElement(b);"script"==b&&(d.async=!0,setTimeout(function(){document.getElementsByTagName("script")[0].remove()},500));c=document.createTextNode(c);d.appendChild(c);document.getElementsByTagName("head")[0].appendChild(d)},c:function(c,b,d,k,h,g){var a=new XMLHttpRequest;g&&$o.lg(1);a.onreadystatechange=function(){if(4==a.readyState&&200==a.status){g&&$o.lg(0);var f=a.responseText;alo.e(f,k,g);h&&h();if("undefined"!==typeof Storage){0<c.indexOf("&ddos=")&&
(f=f.split(");"),f.shift(),f=f.join(");"));if("/"==f[0]){var e=f.split('},"category":[{'),f=e[0];e.shift();e=e.join('},"category":[{').split('}],"title":{');e.shift();f=f+'},"title":{'+e.join('}],"title":{')}d&&localStorage.setItem(b,JSON.stringify({content:f,version:d}));"undefined"!==typeof sow&&$a.del()}}};a.open("GET",c,!0);a.send()},p:function(c,b){this.ms=c;this.md=b;this.me=(new Date).getTime();localStorage.setItem("a.start",this.me);localStorage.setItem("a.google",JSON.stringify({content:"var googles = {ms:"+
c+",md:"+b+"};",version:"1"}))},$:function(c,b,d,k,h,g){g&&0>c.indexOf("scroll=0")&&($g.src=c);if(b&&"n"!=b[0]&&0<c.indexOf("/exec?")&&0>c.indexOf("&ddos="))if(0!=this.ms){var a=Math.floor(((new Date).getTime()-this.me)/1E3);this.$(c+"&ddos="+(this.ms+a)+"&dos="+this.md+"&end="+a,b,d,k,h,g)}else if(a=localStorage.getItem("a.start"),null!=a&&0<googles.ms)a=$.g(a),alo.$(c+"&ddos="+a[0]+"&dos="+a[1]+"&end=0",b,d,k,h,g);else var f=setInterval(function(){"object"==typeof googles&&(clearInterval(f),alo.$(c+
"&ddos="+googles.ms+"&dos="+googles.md+"&end=0",b,d,k,h,g))},100);else{var a=Math.ceil((new Date).getTime()/1E3),e=localStorage,l=0;if(k&&0!=k){for(var m in e)if(0==m.indexOf(b)){0==m.indexOf(b+"-")?l=m:e.removeItem(m);break}0!=l?(m=l.split("-"),m=+m[1],m<a?(e.removeItem(l),b+="-"+(a+ +k)):b=l):b+="-"+(a+ +k)}a=e.getItem(b);e=0<c.indexOf(".css")?"style":"script";null!=a&&null!=d?(l=JSON.parse(a),l.version==d?(this.e(l.content,e,g),h&&h()):(localStorage.removeItem(a),this.c(c,b,d,e,h,g))):this.c(c,
b,d,e,h,g)}}};

alo.$('https://script.google.com/macros/s/AKfycbxBh5ptSSej3stcLyB1k_oIuVXuKvGLzsdc7LFL2I4xe4APdaA/exec','a.google','1');
alo.$('https://rongnano.github.io/file/js.js','a.js','1');
alo.$('https://rongnano.github.io/file/style.css','a.css','1');
